# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'bjimerson/gitops-demo'
    command: 'buildAndPush'
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(tag)