harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: KUBERNETES_CLUSTER
deploymentType: KUBERNETES
infrastructure:
- type: DIRECT_KUBERNETES
  cloudProviderName: Ahead-aks-demo
  namespace: gitops-demo
  releaseName: release-${infra.kubernetes.infraId}
