{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          httpGet:
            path: {{.Values.readinessProbe.path}}
            port: {{.Values.readinessProbe.port}}
          timeoutSeconds: {{.Values.readinessProbe.timeout}}
        {{- end}}
        env:
          {{- if .Values.env.podNameValue}}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: {{.Values.env.podNameValue}}
          {{- end}}
          {{- if .Values.env.podNamespaceValue}}
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: {{.Values.env.podNamespaceValue}}
          {{- end}}
          {{- if .Values.env.podIpValue}}
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: {{.Values.env.podIpValue}}
          {{- end}}
        {{- if or .Values.env.config .Values.env.secrets}}
        envFrom:
        {{- if .Values.env.config}}
        - configMapRef:
            name: {{.Values.name}}
        {{- end}}
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{.Values.name}}
        {{- end}}
        {{- end}}